USE [UserStore]
GO

SELECT * FROM [Roles]
SELECT * FROM [Users]
SELECT * FROM [UserRoles]
SELECT * FROM [UserLogins]
SELECT * FROM [UserClaims]
SELECT * FROM [TotpTokens]
SELECT * FROM [AuthenticationCodeDictionary]
SELECT * FROM [RefreshTokenDictionary]
SELECT * FROM [CustomizedConfirmation]
SELECT * FROM [Saml2OAuth2Data]
SELECT * FROM [FIDO2Data]
SELECT * FROM [IssuedToken]
SELECT * FROM [RequestObject]