SELECT * FROM "Roles";
SELECT * FROM "Users";
SELECT * FROM "UserRoles";
SELECT * FROM "UserLogins";
SELECT * FROM "UserClaims";
SELECT * FROM "AuthenticationCodeDictionary";
SELECT * FROM "RefreshTokenDictionary";
SELECT * FROM "CustomizedConfirmation";
SELECT * FROM "OAuth2Data";