//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPurposeAuthSite.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountViews() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPurposeAuthSite.Resources.AccountViews", typeof(AccountViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Terms of agreement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I accept this term in this agreement. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AgreementCheck {
            get {
                return ResourceManager.GetString("AgreementCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please read the following agreement carefully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AgreementH4 {
            get {
                return ResourceManager.GetString("AgreementH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agreement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AgreementTitle {
            get {
                return ResourceManager.GetString("AgreementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please click here to Log in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmailConfirmationActionLink {
            get {
                return ResourceManager.GetString("EmailConfirmationActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thank you for confirming your email. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmailConfirmationP {
            get {
                return ResourceManager.GetString("EmailConfirmationP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail address was confirmed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmailConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsuccessful login with service. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalLoginFailureH3 {
            get {
                return ResourceManager.GetString("ExternalLoginFailureH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External login was failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalLoginFailureTitle {
            get {
                return ResourceManager.GetString("ExternalLoginFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use another service to log in. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalLoginsListPartialH4 {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartialH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no external authentication services configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalLoginsListPartialP {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartialP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log in using your {0} account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalLoginsListPartialSubmit {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartialSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check your email to reset your password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForgotPasswordConfirmationP {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation for forgotten password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForgotPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter your e-mail address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForgotPasswordH4 {
            get {
                return ResourceManager.GetString("ForgotPasswordH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send link to e-mail address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForgotPasswordSubmit {
            get {
                return ResourceManager.GetString("ForgotPasswordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forgot your password ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Social login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginExternalLogins {
            get {
                return ResourceManager.GetString("LoginExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forgot your password ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginForgotPasswordActionLink {
            get {
                return ResourceManager.GetString("LoginForgotPasswordActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a local account to sign in. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginH4 {
            get {
                return ResourceManager.GetString("LoginH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register as a new user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginRegisterActionLink {
            get {
                return ResourceManager.GetString("LoginRegisterActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign-in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginSubmit {
            get {
                return ResourceManager.GetString("LoginSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign-in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grant に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OAuthAuthorizeGrantButton {
            get {
                return ResourceManager.GetString("OAuthAuthorizeGrantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OAuthAuthorizeP1 {
            get {
                return ResourceManager.GetString("OAuthAuthorizeP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A third party application want to do the following on your behalf: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OAuthAuthorizeP2 {
            get {
                return ResourceManager.GetString("OAuthAuthorizeP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in as different user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OAuthAuthorizeSIDUButton {
            get {
                return ResourceManager.GetString("OAuthAuthorizeSIDUButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorization of resource access. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OAuthAuthorizeTitle {
            get {
                return ResourceManager.GetString("OAuthAuthorizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegisterH4 {
            get {
                return ResourceManager.GetString("RegisterH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegisterSubmit {
            get {
                return ResourceManager.GetString("RegisterSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign-up. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please click here to log in. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPasswordConfirmationActionLink {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your password has been reset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPasswordConfirmationP {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password was reset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset your password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPasswordH4 {
            get {
                return ResourceManager.GetString("ResetPasswordH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPasswordSubmit {
            get {
                return ResourceManager.GetString("ResetPasswordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Two-Factor Authentication Provider: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendCodeDiv {
            get {
                return ResourceManager.GetString("SendCodeDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send verification code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendCodeH4 {
            get {
                return ResourceManager.GetString("SendCodeH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendCodeSubmit {
            get {
                return ResourceManager.GetString("SendCodeSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendCodeTitle {
            get {
                return ResourceManager.GetString("SendCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter verification code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyCodeH4 {
            get {
                return ResourceManager.GetString("VerifyCodeH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyCodeSubmit {
            get {
                return ResourceManager.GetString("VerifyCodeSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyCodeTitle {
            get {
                return ResourceManager.GetString("VerifyCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check your email and confirm your email address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyEmailAddressP {
            get {
                return ResourceManager.GetString("VerifyEmailAddressP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify your e-mail address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyEmailAddressTitle {
            get {
                return ResourceManager.GetString("VerifyEmailAddressTitle", resourceCulture);
            }
        }
    }
}
