//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPurposeAuthSite.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationOAuthBearerTokenProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationOAuthBearerTokenProvider() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPurposeAuthSite.Resources.ApplicationOAuthBearerTokenProvider", typeof(ApplicationOAuthBearerTokenProvider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The resource owner credentials are invalid or resource owner does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client Credentials grant type is not enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnableClientCredentialsGrantType {
            get {
                return ResourceManager.GetString("EnableClientCredentialsGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh Token is not enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnableRefreshToken {
            get {
                return ResourceManager.GetString("EnableRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ResourceOwner Credentials grant type is not enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnableResourceOwnerCredentialsGrantType {
            get {
                return ResourceManager.GetString("EnableResourceOwnerCredentialsGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve the user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_error1 {
            get {
                return ResourceManager.GetString("server_error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ClaimsIdentity could not be created by the UserManager. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_error2 {
            get {
                return ResourceManager.GetString("server_error2", resourceCulture);
            }
        }
    }
}
