//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPurposeAuthSite.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonViewModels() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPurposeAuthSite.Resources.CommonViewModels", typeof(CommonViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ClientID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClientSecret に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm new password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The new password and confirmation password do not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmNewPasswordErrMsg {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password and confirmation password do not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmPasswordErrMsg {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} must be at least {2} characters long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordLengthErrMsg {
            get {
                return ResourceManager.GetString("PasswordLengthErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payment Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RedirectUriCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriCode {
            get {
                return ResourceManager.GetString("RedirectUriCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RedirectUriToken に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriToken {
            get {
                return ResourceManager.GetString("RedirectUriToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember this browser ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember me ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnstructuredData1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnstructuredData1 {
            get {
                return ResourceManager.GetString("UnstructuredData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnstructuredData2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnstructuredData2 {
            get {
                return ResourceManager.GetString("UnstructuredData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by user name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserNameforSearch {
            get {
                return ResourceManager.GetString("UserNameforSearch", resourceCulture);
            }
        }
    }
}
