//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPurposeAuthSite.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManageController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageController() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPurposeAuthSite.Resources.ManageController", typeof(ManageController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Account do not match in social login. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountConflictInSocialLogin {
            get {
                return ResourceManager.GetString("AccountConflictInSocialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your E-mail has not been added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddEmailFailure {
            get {
                return ResourceManager.GetString("AddEmailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your E-mail has been added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddEmailSuccess {
            get {
                return ResourceManager.GetString("AddEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your payment information has been added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddPaymentInformationSuccess {
            get {
                return ResourceManager.GetString("AddPaymentInformationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your phone number has been added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddPhoneSuccess {
            get {
                return ResourceManager.GetString("AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your additional attribute data has been added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddUnstructuredDataSuccess {
            get {
                return ResourceManager.GetString("AddUnstructuredDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your E-mail has not been changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeEmailFailure {
            get {
                return ResourceManager.GetString("ChangeEmailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your E-mail has been changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeEmailSuccess {
            get {
                return ResourceManager.GetString("ChangeEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your password has been changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your user name has not been changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeUserNameFailure {
            get {
                return ResourceManager.GetString("ChangeUserNameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your user name has been changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeUserNameSuccess {
            get {
                return ResourceManager.GetString("ChangeUserNameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your security code is: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CodeForAddPhoneNumber {
            get {
                return ResourceManager.GetString("CodeForAddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The entered ID (mail address) is already in use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnteredIdIsAlreadyExists {
            get {
                return ResourceManager.GetString("EnteredIdIsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to verify your phone number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedVerifyPhoneNumber {
            get {
                return ResourceManager.GetString("FailedVerifyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your E-mail has been removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveEmailSuccess {
            get {
                return ResourceManager.GetString("RemoveEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The external login has been removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveExternalLoginSuccess {
            get {
                return ResourceManager.GetString("RemoveExternalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your payment information has been removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemovePaymentInformationSuccess {
            get {
                return ResourceManager.GetString("RemovePaymentInformationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your phone number has been removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemovePhoneSuccess {
            get {
                return ResourceManager.GetString("RemovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your additional attribute data has been removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveUnstructuredDataSuccess {
            get {
                return ResourceManager.GetString("RemoveUnstructuredDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your password has been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetPasswordSuccess {
            get {
                return ResourceManager.GetString("SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your two-factor authentication provider has been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetTwoFactorSuccess {
            get {
                return ResourceManager.GetString("SetTwoFactorSuccess", resourceCulture);
            }
        }
    }
}
