//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPurposeAuthSite.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminViews() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPurposeAuthSite.Resources.AdminViews", typeof(AdminViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Back to List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnList {
            get {
                return ResourceManager.GetString("ReturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new role. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminCreateH4 {
            get {
                return ResourceManager.GetString("RolesAdminCreateH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminCreateSubmit {
            get {
                return ResourceManager.GetString("RolesAdminCreateSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create role に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminCreateTitle {
            get {
                return ResourceManager.GetString("RolesAdminCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this Role ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDeleteB {
            get {
                return ResourceManager.GetString("RolesAdminDeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this role. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDeleteH4 {
            get {
                return ResourceManager.GetString("RolesAdminDeleteH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting this Role will remove all users from this role. It will not delete the users. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDeleteP {
            get {
                return ResourceManager.GetString("RolesAdminDeleteP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDeleteSubmit {
            get {
                return ResourceManager.GetString("RolesAdminDeleteSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete role に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDeleteTitle {
            get {
                return ResourceManager.GetString("RolesAdminDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDetailsH4 {
            get {
                return ResourceManager.GetString("RolesAdminDetailsH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No users found in this role. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDetailsNoUsers {
            get {
                return ResourceManager.GetString("RolesAdminDetailsNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDetailsTitle {
            get {
                return ResourceManager.GetString("RolesAdminDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of users in this role. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminDetailsUserList {
            get {
                return ResourceManager.GetString("RolesAdminDetailsUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit role form. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminEditH4 {
            get {
                return ResourceManager.GetString("RolesAdminEditH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminEditSubmit {
            get {
                return ResourceManager.GetString("RolesAdminEditSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Role に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminEditTitle {
            get {
                return ResourceManager.GetString("RolesAdminEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminIndexCreate {
            get {
                return ResourceManager.GetString("RolesAdminIndexCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roles list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminIndexTitle {
            get {
                return ResourceManager.GetString("RolesAdminIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesAdminRoleName {
            get {
                return ResourceManager.GetString("RolesAdminRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminCreateH4 {
            get {
                return ResourceManager.GetString("UsersAdminCreateH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select User Role に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminCreateSelectRoles {
            get {
                return ResourceManager.GetString("UsersAdminCreateSelectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminCreateSubmit {
            get {
                return ResourceManager.GetString("UsersAdminCreateSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminCreateTitle {
            get {
                return ResourceManager.GetString("UsersAdminCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this User? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDeleteB {
            get {
                return ResourceManager.GetString("UsersAdminDeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDeleteH4 {
            get {
                return ResourceManager.GetString("UsersAdminDeleteH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDeleteSubmit {
            get {
                return ResourceManager.GetString("UsersAdminDeleteSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDeleteTitle {
            get {
                return ResourceManager.GetString("UsersAdminDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDetailsH4 {
            get {
                return ResourceManager.GetString("UsersAdminDetailsH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No roles found for this user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDetailsNoRoles {
            get {
                return ResourceManager.GetString("UsersAdminDetailsNoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of roles for this user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDetailsRoleList {
            get {
                return ResourceManager.GetString("UsersAdminDetailsRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminDetailsTitle {
            get {
                return ResourceManager.GetString("UsersAdminDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit user form. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminEditH4 {
            get {
                return ResourceManager.GetString("UsersAdminEditH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminEditSubmit {
            get {
                return ResourceManager.GetString("UsersAdminEditSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminEditTitle {
            get {
                return ResourceManager.GetString("UsersAdminEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminIndexCreate {
            get {
                return ResourceManager.GetString("UsersAdminIndexCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminIndexTitle {
            get {
                return ResourceManager.GetString("UsersAdminIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsersAdminUserName {
            get {
                return ResourceManager.GetString("UsersAdminUserName", resourceCulture);
            }
        }
    }
}
