//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPurposeAuthSite.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonViewModels() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPurposeAuthSite.Resources.CommonViewModels", typeof(CommonViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Specify redirect_uri at the time of test. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClarifyRedirectUri {
            get {
                return ResourceManager.GetString("ClarifyRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   client_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OAuth2/OIDC mode of Client. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientMode {
            get {
                return ResourceManager.GetString("ClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   client_secret に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client type to restrict the flow. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm new E-mail address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmNewEmail {
            get {
                return ResourceManager.GetString("ConfirmNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The new E-mail address and confirmation E-mail address do not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmNewEmailErrMsg {
            get {
                return ResourceManager.GetString("ConfirmNewEmailErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm new password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The new password and confirmation password do not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmNewPasswordErrMsg {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password and confirmation password do not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmPasswordErrMsg {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JWK&apos;s ECDSA public key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JwkECDsaPublickey {
            get {
                return ResourceManager.GetString("JwkECDsaPublickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JWK&apos;s RSA public key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JwkRsaPublickey {
            get {
                return ResourceManager.GetString("JwkRsaPublickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} must be at less than or equal to {1} characters long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxLengthErrMsg {
            get {
                return ResourceManager.GetString("MaxLengthErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New E-mail address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New user name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewUserName {
            get {
                return ResourceManager.GetString("NewUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payment Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   post_logout_redirect_uri に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostLogoutRedirectUri {
            get {
                return ResourceManager.GetString("PostLogoutRedirectUri", resourceCulture);
            }
        }

        /// <summary>
        ///   redirect_uri_code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriCode {
            get {
                return ResourceManager.GetString("RedirectUriCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   redirect_uri_saml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriSaml {
            get {
                return ResourceManager.GetString("RedirectUriSaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   redirect_uri_token に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriToken {
            get {
                return ResourceManager.GetString("RedirectUriToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember this browser ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember me ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Require PKCE for this client. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequirePkce {
            get {
                return ResourceManager.GetString("RequirePkce", resourceCulture);
            }
        }

        /// <summary>
        ///   OAuth2/OIDC ResponseMode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResponseMode {
            get {
                return ResourceManager.GetString("ResponseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject Identifier types に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubjectTypes {
            get {
                return ResourceManager.GetString("SubjectTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   CORS allowed origins (web_origins) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebOrigins {
            get {
                return ResourceManager.GetString("WebOrigins", resourceCulture);
            }
        }

        /// <summary>
        ///   Request object signing algorithm (request_object_signing_alg) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestObjectSigningAlg {
            get {
                return ResourceManager.GetString("RequestObjectSigningAlg", resourceCulture);
            }
        }

        /// <summary>
        ///   Client assertion signing algorithm (token_endpoint_auth_signing_alg) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenEndpointAuthSigningAlg {
            get {
                return ResourceManager.GetString("TokenEndpointAuthSigningAlg", resourceCulture);
            }
        }

        /// <summary>
        ///   Signing algorithm (id_token_signed_response_alg) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IdTokenSignedResponseAlg {
            get {
                return ResourceManager.GetString("IdTokenSignedResponseAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DN of the client certificate to use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TlsClientAuthSubjectDn {
            get {
                return ResourceManager.GetString("TlsClientAuthSubjectDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnstructuredData1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnstructuredData1 {
            get {
                return ResourceManager.GetString("UnstructuredData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnstructuredData2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnstructuredData2 {
            get {
                return ResourceManager.GetString("UnstructuredData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   User name or e-mail address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserNameOrEmail {
            get {
                return ResourceManager.GetString("UserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by user name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserNameforSearch {
            get {
                return ResourceManager.GetString("UserNameforSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClientIDDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientIDDescription {
            get {
                return ResourceManager.GetString("ClientIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClientSecretDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientSecretDescription {
            get {
                return ResourceManager.GetString("ClientSecretDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClientModeDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientModeDescription {
            get {
                return ResourceManager.GetString("ClientModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RequirePkceDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequirePkceDescription {
            get {
                return ResourceManager.GetString("RequirePkceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RedirectUriSamlDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriSamlDescription {
            get {
                return ResourceManager.GetString("RedirectUriSamlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RedirectUriCodeDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriCodeDescription {
            get {
                return ResourceManager.GetString("RedirectUriCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RedirectUriTokenDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedirectUriTokenDescription {
            get {
                return ResourceManager.GetString("RedirectUriTokenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PostLogoutRedirectUriDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostLogoutRedirectUriDescription {
            get {
                return ResourceManager.GetString("PostLogoutRedirectUriDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SubjectTypesDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubjectTypesDescription {
            get {
                return ResourceManager.GetString("SubjectTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebOriginsDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebOriginsDescription {
            get {
                return ResourceManager.GetString("WebOriginsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IdTokenSignedResponseAlgDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IdTokenSignedResponseAlgDescription {
            get {
                return ResourceManager.GetString("IdTokenSignedResponseAlgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TokenEndpointAuthSigningAlgDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenEndpointAuthSigningAlgDescription {
            get {
                return ResourceManager.GetString("TokenEndpointAuthSigningAlgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RequestObjectSigningAlgDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestObjectSigningAlgDescription {
            get {
                return ResourceManager.GetString("RequestObjectSigningAlgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JwkRsaPublickeyDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JwkRsaPublickeyDescription {
            get {
                return ResourceManager.GetString("JwkRsaPublickeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TlsClientAuthSubjectDnDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TlsClientAuthSubjectDnDescription {
            get {
                return ResourceManager.GetString("TlsClientAuthSubjectDnDescription", resourceCulture);
            }
        }
    }
}
