//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPurposeAuthSite.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManageViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageViews() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPurposeAuthSite.Resources.ManageViews", typeof(ManageViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add E-mail form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddEmailH4 {
            get {
                return ResourceManager.GetString("AddEmailH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddEmailSubmit {
            get {
                return ResourceManager.GetString("AddEmailSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddEmailTitle {
            get {
                return ResourceManager.GetString("AddEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Microsoft Passport data form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddMsPassDataH4 {
            get {
                return ResourceManager.GetString("AddMsPassDataH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Microsoft Passport 2 authenticator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddMsPassDataSubmit {
            get {
                return ResourceManager.GetString("AddMsPassDataSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Microsoft Passport data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddMsPassDataTitle {
            get {
                return ResourceManager.GetString("AddMsPassDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add OAuth2 data form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddSaml2OAuth2DataH4 {
            get {
                return ResourceManager.GetString("AddSaml2OAuth2DataH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddSaml2OAuth2DataSubmit {
            get {
                return ResourceManager.GetString("AddSaml2OAuth2DataSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add OAuth2 data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddSaml2OAuth2DataTitle {
            get {
                return ResourceManager.GetString("AddSaml2OAuth2DataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add payment information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddPaymentH4 {
            get {
                return ResourceManager.GetString("AddPaymentH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddPaymentSubmit {
            get {
                return ResourceManager.GetString("AddPaymentSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add payment information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddPaymentTitle {
            get {
                return ResourceManager.GetString("AddPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add phone number form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddPhoneNumberH4 {
            get {
                return ResourceManager.GetString("AddPhoneNumberH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddPhoneNumberSubmit {
            get {
                return ResourceManager.GetString("AddPhoneNumberSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add phone number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddPhoneNumberTitle {
            get {
                return ResourceManager.GetString("AddPhoneNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add attribute data form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddUnstructuredDataH4 {
            get {
                return ResourceManager.GetString("AddUnstructuredDataH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddUnstructuredDataSubmit {
            get {
                return ResourceManager.GetString("AddUnstructuredDataSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add attribute data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddUnstructuredDataTitle {
            get {
                return ResourceManager.GetString("AddUnstructuredDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add WebAuthn data form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddWebAuthnDataH4 {
            get {
                return ResourceManager.GetString("AddWebAuthnDataH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register WebAuthn authenticator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddWebAuthnDataSubmit {
            get {
                return ResourceManager.GetString("AddWebAuthnDataSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add WebAuthn data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddWebAuthnDataTitle {
            get {
                return ResourceManager.GetString("AddWebAuthnDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change E-mail form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeEmailH4 {
            get {
                return ResourceManager.GetString("ChangeEmailH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeEmailSubmit {
            get {
                return ResourceManager.GetString("ChangeEmailSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeEmailTitle {
            get {
                return ResourceManager.GetString("ChangeEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change password form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordH4 {
            get {
                return ResourceManager.GetString("ChangePasswordH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordSubmit {
            get {
                return ResourceManager.GetString("ChangePasswordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change user name form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeUserNameH4 {
            get {
                return ResourceManager.GetString("ChangeUserNameH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeUserNameSubmit {
            get {
                return ResourceManager.GetString("ChangeUserNameSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change user name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeUserNameTitle {
            get {
                return ResourceManager.GetString("ChangeUserNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete your GDPR personal data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteGdprPersonalDataSubmit {
            get {
                return ResourceManager.GetString("DeleteGdprPersonalDataSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableTwoFactorAuthenticatorGenCode {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthenticatorGenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To use an authenticator app go through the following steps: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableTwoFactorAuthenticatorH {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthenticatorH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download a two-factor authenticator app like Microsoft Authenticator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableTwoFactorAuthenticatorP {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthenticatorP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan the QR Code or enter this key [{0}] into your two factor authenticator app. Spaces and casing do not matter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableTwoFactorAuthenticatorQRCode {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthenticatorQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableTwoFactorAuthenticatorSubmit {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthenticatorSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable TOTP Two-factor authenticator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableTwoFactorAuthenticatorTitle {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthenticatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This action generates new recovery codes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateTwoFactorAuthenticatorRecoveryCodesH {
            get {
                return ResourceManager.GetString("GenerateTwoFactorAuthenticatorRecoveryCodesH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you lose your device and don&apos;t have the recovery codes you will lose access to your account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateTwoFactorAuthenticatorRecoveryCodesP1 {
            get {
                return ResourceManager.GetString("GenerateTwoFactorAuthenticatorRecoveryCodesP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should reset your authenticator keys. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateTwoFactorAuthenticatorRecoveryCodesP2 {
            get {
                return ResourceManager.GetString("GenerateTwoFactorAuthenticatorRecoveryCodesP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate Recovery Codes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateTwoFactorAuthenticatorRecoveryCodesSubmit {
            get {
                return ResourceManager.GetString("GenerateTwoFactorAuthenticatorRecoveryCodesSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate TOTP Two-factor authenticator recovery codes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateTwoFactorAuthenticatorRecoveryCodesTitle {
            get {
                return ResourceManager.GetString("GenerateTwoFactorAuthenticatorRecoveryCodesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexChangePasswordActionLink {
            get {
                return ResourceManager.GetString("IndexChangePasswordActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your client_id data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexClientIDChangeButton {
            get {
                return ResourceManager.GetString("IndexClientIDChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your client_secret data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexClientSecretChangeButton {
            get {
                return ResourceManager.GetString("IndexClientSecretChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexEmail {
            get {
                return ResourceManager.GetString("IndexEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add your E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexEmailAddActionLink {
            get {
                return ResourceManager.GetString("IndexEmailAddActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexEmailChangeActionLink {
            get {
                return ResourceManager.GetString("IndexEmailChangeActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove your E-mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexEmailRemoveButton {
            get {
                return ResourceManager.GetString("IndexEmailRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External logins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexExternalLogins {
            get {
                return ResourceManager.GetString("IndexExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexExternalLoginsActionLink {
            get {
                return ResourceManager.GetString("IndexExternalLoginsActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your account settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexH4 {
            get {
                return ResourceManager.GetString("IndexH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gdpr personal data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexManageGdprData {
            get {
                return ResourceManager.GetString("IndexManageGdprData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Passport data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexMsPassData {
            get {
                return ResourceManager.GetString("IndexMsPassData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add your Microsoft Passport data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexMsPassDataAddActionLink {
            get {
                return ResourceManager.GetString("IndexMsPassDataAddActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove your Microsoft Passport data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexMsPassDataRemoveButton {
            get {
                return ResourceManager.GetString("IndexMsPassDataRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OAuth2 data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexSaml2OAuth2Data {
            get {
                return ResourceManager.GetString("IndexSaml2OAuth2Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add your OAuth2 data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexSaml2OAuth2DataAddActionLink {
            get {
                return ResourceManager.GetString("IndexSaml2OAuth2DataAddActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your OAuth2 data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexSaml2OAuth2DataChangeActionLink {
            get {
                return ResourceManager.GetString("IndexSaml2OAuth2DataChangeActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove your OAuth2 data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexSaml2OAuth2DataRemoveButton {
            get {
                return ResourceManager.GetString("IndexSaml2OAuth2DataRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get your OAuth2 access token に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexOAuth2TokenGetButton {
            get {
                return ResourceManager.GetString("IndexOAuth2TokenGetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To charge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPaymentButton {
            get {
                return ResourceManager.GetString("IndexPaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payment information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPaymentInformation {
            get {
                return ResourceManager.GetString("IndexPaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add your payment information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPaymentInformationAddActionLink {
            get {
                return ResourceManager.GetString("IndexPaymentInformationAddActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your payment information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPaymentInformationChangeActionLink {
            get {
                return ResourceManager.GetString("IndexPaymentInformationChangeActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove your payment information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPaymentInformationRemoveButton {
            get {
                return ResourceManager.GetString("IndexPaymentInformationRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPhoneNumber {
            get {
                return ResourceManager.GetString("IndexPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add your phone number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPhoneNumberAddActionLink {
            get {
                return ResourceManager.GetString("IndexPhoneNumberAddActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your phone number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPhoneNumberChangeActionLink {
            get {
                return ResourceManager.GetString("IndexPhoneNumberChangeActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove your phone number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexPhoneNumberRemoveButton {
            get {
                return ResourceManager.GetString("IndexPhoneNumberRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create your password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexSetPasswordActionLink {
            get {
                return ResourceManager.GetString("IndexSetPasswordActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two-Factor authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexTwoFactorAuth {
            get {
                return ResourceManager.GetString("IndexTwoFactorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexTwoFactorAuthDisableStatus {
            get {
                return ResourceManager.GetString("IndexTwoFactorAuthDisableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexTwoFactorAuthEnableStatus {
            get {
                return ResourceManager.GetString("IndexTwoFactorAuthEnableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexTwoFactorAuthToDisabledButton {
            get {
                return ResourceManager.GetString("IndexTwoFactorAuthToDisabledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexTwoFactorAuthToEnabledButton {
            get {
                return ResourceManager.GetString("IndexTwoFactorAuthToEnabledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attribute data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexUnstructuredData {
            get {
                return ResourceManager.GetString("IndexUnstructuredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add your attribute data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexUnstructuredDataAddActionLink {
            get {
                return ResourceManager.GetString("IndexUnstructuredDataAddActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your attribute data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexUnstructuredDataChangeActionLink {
            get {
                return ResourceManager.GetString("IndexUnstructuredDataChangeActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove your attribute data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexUnstructuredDataRemoveButton {
            get {
                return ResourceManager.GetString("IndexUnstructuredDataRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change your user name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexUserNameChangeActionLink {
            get {
                return ResourceManager.GetString("IndexUserNameChangeActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebAuthn data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexWebAuthnData {
            get {
                return ResourceManager.GetString("IndexWebAuthnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add your WebAuthn data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexWebAuthnDataAddActionLink {
            get {
                return ResourceManager.GetString("IndexWebAuthnDataAddActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove your WebAuthn data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexWebAuthnDataRemoveButton {
            get {
                return ResourceManager.GetString("IndexWebAuthnDataRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GDPR personal data management form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageGdprPersonalDataH4 {
            get {
                return ResourceManager.GetString("ManageGdprPersonalDataH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Management of GDPR personal data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageGdprPersonalDataTitle {
            get {
                return ResourceManager.GetString("ManageGdprPersonalDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log in using your {0} account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageLoginsAddButtonTitle {
            get {
                return ResourceManager.GetString("ManageLoginsAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no external authentication services configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageLoginsNoExternalAuthSvc {
            get {
                return ResourceManager.GetString("ManageLoginsNoExternalAuthSvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other external logins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageLoginsNonRegistered {
            get {
                return ResourceManager.GetString("ManageLoginsNonRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered external logins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageLoginsRegistered {
            get {
                return ResourceManager.GetString("ManageLoginsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageLoginsRemoveButton {
            get {
                return ResourceManager.GetString("ManageLoginsRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove this {0} login from your account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageLoginsRemoveButtonTitle {
            get {
                return ResourceManager.GetString("ManageLoginsRemoveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage your external logins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageLoginsTitle {
            get {
                return ResourceManager.GetString("ManageLoginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authenticator app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorAppH {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorAppH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have no recovery codes left. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorCodesLeft0H {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorCodesLeft0H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have 1 recovery code left. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorCodesLeft1H {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorCodesLeft1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have {0} recovery codes left. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorCodesLeft3H {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorCodesLeft3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add authenticator app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorSubmitAAA {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorSubmitAAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure authenticator app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorSubmitCAA {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorSubmitCAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset authenticator app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorSubmitRAA {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorSubmitRAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset recovery codes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorSubmitRRC {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorSubmitRRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage TOTP Two-factor authenticator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageTwoFactorAuthenticatorTitle {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuthenticatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refer your GDPR personal data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReferGdprPersonalDataSubmit {
            get {
                return ResourceManager.GetString("ReferGdprPersonalDataSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove WebAuthn data form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveWebAuthnDataH4 {
            get {
                return ResourceManager.GetString("RemoveWebAuthnDataH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove WebAuthn authenticator&apos;s key  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveWebAuthnDataSubmit {
            get {
                return ResourceManager.GetString("RemoveWebAuthnDataSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove WebAuthn data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveWebAuthnDataTitle {
            get {
                return ResourceManager.GetString("RemoveWebAuthnDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you reset your authenticator key your authenticator app will not work until you reconfigure it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetTwoFactorAuthenticatorH {
            get {
                return ResourceManager.GetString("ResetTwoFactorAuthenticatorH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This process disables 2FA until you verify your authenticator app and will also reset your 2FA recovery codes. If you do not complete your authenticator app configuration you may lose access to your account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetTwoFactorAuthenticatorP {
            get {
                return ResourceManager.GetString("ResetTwoFactorAuthenticatorP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset authenticator key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetTwoFactorAuthenticatorSubmit {
            get {
                return ResourceManager.GetString("ResetTwoFactorAuthenticatorSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset TOTP Two-factor authenticator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetTwoFactorAuthenticatorTitle {
            get {
                return ResourceManager.GetString("ResetTwoFactorAuthenticatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create local login form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetPasswordH4 {
            get {
                return ResourceManager.GetString("SetPasswordH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have a local password for this site. Add a local password so you can log in without an external login. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetPasswordP {
            get {
                return ResourceManager.GetString("SetPasswordP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetPasswordSubmit {
            get {
                return ResourceManager.GetString("SetPasswordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create local login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetPasswordTitle {
            get {
                return ResourceManager.GetString("SetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Put these codes in a safe place. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowTwoFactorAuthenticatorRecoveryCodesH {
            get {
                return ResourceManager.GetString("ShowTwoFactorAuthenticatorRecoveryCodesH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you lose your device and don&apos;t have the recovery codes you will lose access to your account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowTwoFactorAuthenticatorRecoveryCodesP {
            get {
                return ResourceManager.GetString("ShowTwoFactorAuthenticatorRecoveryCodesP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage TOTP Two-factor authenticator recovery codes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowTwoFactorAuthenticatorRecoveryCodesTitle {
            get {
                return ResourceManager.GetString("ShowTwoFactorAuthenticatorRecoveryCodesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter verification code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyPhoneNumberH4 {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyPhoneNumberSubmit {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Phone Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyPhoneNumberTitle {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberTitle", resourceCulture);
            }
        }
    }
}
